# Generated by Django 5.2.14 on 2026-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='segments',
            field=models.JSONField(default=list),
        ),
    ]
