# Generated by Django 5.2.14 on 2026-07-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inp', '0003_transcript_created_at_transcript_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='video_file',
        ),
        migrations.AddField(
            model_name='transcript',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
